---
adgroup: false
model:
  name: project-member
  defaults: {}
members:
- username: man
  access: RO
  workspace_name: manual_ws
- access: RW
  workspace_name: office
  username: rmittal
- access: RO
  workspace_name: office
  username: rmittal
deprovision: false
trigger:
  mapping:
    access: $.fields.customfield_10205.value
    workspace_name: $.fields.customfield_10207.value
    username: $.fields.reporter.emailAddress
  config:
    query: "project = ServiceTitan-Demo AND \"Approvals[Approvals]\" = approved() AND status in (\"Waiting for support\") AND \"Request Type\" = \"Request Access To A Snowflake Workspace\" AND createdDate > -14d ORDER BY updatedDate"
  removeDomain:
  - username
