name: serviceTitan
on: 
  workflow_dispatch:
  push:
#   schedule:
#     - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STACK_PATH: ${{ secrets.STACK_PATH }}
      TRAM_TRIGGER_GIT_REMOTE_PASSWORD: ${{ secrets.TRAM_TRIGGER_GIT_REMOTE_PASSWORD}}
      TRAM_TRIGGER_JIRA_TOKEN: ${{ secrets.TRAM_TRIGGER_JIRA_TOKEN}}
      SNOWFLAKE_USER_PASSWORD: ${{ secrets.SNOWFLAKE_USER_PASSWORD}}
      JAVA_HOME: ${{ secrets.JAVA_HOME}}
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x ./bin/tram-fetch
      - run: export TRAM_ENTITLEMENT_TOKEN=${{env.TRAM_ENTITLEMENT_TOKEN}}
      - run: ./bin/tram-fetch
      - run: chmod +x bin/tram-dry-run
      - run: ./bin/tram-dry-run
      - run: chmod +x bin/tram-provision
      - run: ./bin/tram-provision
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner.."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
